### ISSUE TITLE
Missing "GINN.evaluation" 

### ISSUE THREAD

**Issue by jianwei-liu93** [ml-jku/GINNs-Geometry-informed-Neural-Networks#2]
The "evaluation" folder under "GINN" seems to be missing in the latest version

**Comment by radlera** [comment]
Hi @jianwei-liu93 
Thanks for pointing that out. I just added the evaluation module in this commit: https://github.com/ml-jku/GINNs-Geometry-informed-Neural-Networks/commit/2d8d43df0e10f4579f5b50b0432acee28faba132
